@baseUrl=http://localhost:4000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMTkyZmM1ZS0wMDkzLTdjY2MtYTIwYS1kYzg0NGE1YmFkMWMiLCJpYXQiOjE3MzA4MTI0MjQsImV4cCI6NDg4NDQxMjQyNH0.kpqWbQXwp9GsKhB-Yd1eGPdq8NHw5mj_9xpRT5Ggmkw

### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "Welcome!23"
}

### Register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "username": "bseetha",
    "password": "Welcome!23",
    "email": "bseetha@fandatech.net",
    "phone": "+9789813931",
    "firstName": "Seethalakshmi",
    "lastName": "Balamurugan",
    "role": "Manager"
}

### Profile
GET {{baseUrl}}/api/auth/profile
Content-Type: application/json
Authorization: Bearer {{token}}
