@baseUrl=http://localhost:4000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMTkyZmM1ZS0wMDkzLTdjY2MtYTIwYS1kYzg0NGE1YmFkMWMiLCJpYXQiOjE3MzA4MTI0MjQsImV4cCI6NDg4NDQxMjQyNH0.kpqWbQXwp9GsKhB-Yd1eGPdq8NHw5mj_9xpRT5Ggmkw

### Get all companies
GET {{baseUrl}}/api/companies
Content-Type: application/json
Authorization: Bearer {{token}}

### Get company by id
GET {{baseUrl}}/api/companies/0192a838-1ddf-7337-a6a8-0838ddcea2fb
Content-Type: application/json
Authorization: Bearer {{token}}


### Create company
POST {{baseUrl}}/api/companies
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "code": "FANDA",
  "name": "FandaTech",
  "description": "Fintech company",
  "test":"Testing",
  "address": {
    "line1": "#53/15A, Narayanapalayam string",
    "city": "Kanchipuram",
    "state": "TN",
    "postalCode": "631501",
    "test":"Testing"
  },
  "contact": {
    "phone": "+919840000000",
    "email": "adin@fandatech.net",
    "test":"Testing"
  }
}

### Update company
PUT {{baseUrl}}/api/companies/0193013f-e4bd-7bba-915a-320ce428e8fd
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "contact": {
    "phone": "+919840000000",
    "email": "adin@fandatech.net",
    "test":"Testing"
  }
}

### Delete company
DELETE {{baseUrl}}/api/companies/4d5dc30e-43f1-4ec1-9300-0285a95c768c
Content-Type: application/json
Authorization: Bearer {{token}}