@baseUrl=http://localhost:4000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMTkyZmM1ZS0wMDkzLTdjY2MtYTIwYS1kYzg0NGE1YmFkMWMiLCJpYXQiOjE3MzA4MTI0MjQsImV4cCI6NDg4NDQxMjQyNH0.kpqWbQXwp9GsKhB-Yd1eGPdq8NHw5mj_9xpRT5Ggmkw
@companyId=0193ea18-9b4d-76ac-b03b-79702d1265a0
@categoryId=0193ea18-9b5a-777b-85bf-35a6c63ca1be
@unitId=0193ea18-9b5b-77ba-bcc9-ad330d1262b6
@productId=01932b09-e357-7998-9a52-513d73aef4ba

### Get all products
GET {{baseUrl}}/api/companies/{{companyId}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

### Get product by id
GET {{baseUrl}}/api/companies/{{companyId}}/products/{{productId}}
Content-Type: application/json
Authorization: Bearer {{token}}


### Create product
POST {{baseUrl}}/api/companies/{{companyId}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  # "productId": "{{productId}}",
  "code": "MONITOR",
  "name": "Monitor",
  "description": "Monitors",
  "productType": "goods",
  "categoryId": "{{categoryId}}",
  "baseUnitId": "{{unitId}}",
  "buyingPrice": 20000,
  "marginAmt": 5000,
  "sellingPrice": 15000,
  "taxCode": "G-C00001",
  "taxPct": 18,
  "taxPreference": "taxable",
  "isPriceInclusiveTax": false,
  "gtnGeneration": "tag"
}

### Update product
PUT {{baseUrl}}/api/companies/{{companyId}}/products/{{productId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": "{{productId}}",
  "code": "MONITORS",
  "name": "Monitq",
  "description": "Display monitors",
  "type": "Good",
  "baseUnitId": "{{unitId}}",
  "buyingPrice": 10000,
  "marginAmount": 2500,
  "sellingPrice": 12500,
  "taxCode": "G-M00001",
  "taxPct": 18,
  "taxPreference": "Taxable",
  "isPriceInclusiveTax": true
}

### Delete product
DELETE {{baseUrl}}/api/companies/{{companyId}}/products/{{productId}}
Content-Type: application/json
Authorization: Bearer {{token}}