@baseUrl=http://localhost:4000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMTkyZmM1ZS0wMDkzLTdjY2MtYTIwYS1kYzg0NGE1YmFkMWMiLCJpYXQiOjE3MzA4MTI0MjQsImV4cCI6NDg4NDQxMjQyNH0.kpqWbQXwp9GsKhB-Yd1eGPdq8NHw5mj_9xpRT5Ggmkw
@companyId=0193ea0e-12b0-704e-b888-cf085466b612
@yearId=0193ea0e-12b6-72bf-ae19-45a43fdd19c4
@supplierId=0193ea0e-12c2-7137-8c50-3417ba3dc454
@unitId=0193ea0e-12ca-71ad-a5fd-ec3aa58be8d3
@productId=0193f233-fc38-7360-8bb1-b317340fee32
@productId2=0193f233-fc38-7360-8bb1-b317340fee33


### Get all purchases
GET {{baseUrl}}/api/companies/{{companyId}}/years/{{yearId}}/purchases
Content-Type: application/json
Authorization: Bearer {{token}}


### Get purchase by id
GET {{baseUrl}}/api/companies/{{companyId}}/years/{{yearId}}/purchases/0193f8c5-ca69-73f8-b021-59151522d698
Content-Type: application/json
Authorization: Bearer {{token}}


### Create purchase
POST {{baseUrl}}/api/companies/{{companyId}}/years/{{yearId}}/purchases
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "invoiceDate": "2024-12-24",
  "refNumber": "PU-KD9MD3R43",
  "refDate": "2024-12-24",
  "supplierId": "{{supplierId}}",
  "totalQty": "10",
  "subtotal": "25000",
  "discountAmt": 5000,
  "notes": "This is test purchase",
  "lineItems": [
    {
      "productId": "{{productId}}",
      "unitId": "{{unitId}}",
      "gtn": "tbd",
      "qty": "5",
      "rate": "25000",
      "price": "2000000",
      "discountPct": 10,
      "taxPct": 5,
      "lineTotal": "12500",
      "marginPct": 10
    },
    {
      "productId": "{{productId}}",
      "unitId": "{{unitId}}",
      "gtn": "tbd",
      "qty": "1",
      "rate": "25000",
      "price": "2000000",
      "discountPct": 10,
      "taxPct": 5,
      "lineTotal": "12500",
      "marginPct": 10
    },
    {
      "productId": "{{productId2}}",
      "unitId": "{{unitId}}",
      "gtn": "tbd",
      "qty": "50",
      "rate": "12500",
      "price": "12500",
      "discountPct": 10,
      "taxPct": 5,
      "lineTotal": "12500",
      "marginPct": 10
    },
    {
      "productId": "{{productId2}}",
      "unitId": "{{unitId}}",
      "gtn": "tbd",
      "qty": "1",
      "rate": "12500",
      "price": "12500",
      "discountPct": 10,
      "taxPct": 5,
      "lineTotal": "12500",
      "marginPct": 10
    }
  ]
}


### Update purchase
PUT {{baseUrl}}/api/companies/{{companyId}}/years/{{yearId}}/purchases/d768a1ac-b2a3-4500-9b9d-7d5d00030f95
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "code": "FY-2024-25",
  "beginDate": "2024-04-01",
  "endDate": "2025-03-31"
}


### Delete purchase
DELETE {{baseUrl}}/api/companies/{{companyId}}/years/{{yearId}}/purchases/0193f6e2-8c11-715f-8ea6-af501159be94
Content-Type: application/json
Authorization: Bearer {{token}}