@baseUrl=http://localhost:4000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMTkyZmM1ZS0wMDkzLTdjY2MtYTIwYS1kYzg0NGE1YmFkMWMiLCJpYXQiOjE3MzA4MTI0MjQsImV4cCI6NDg4NDQxMjQyNH0.kpqWbQXwp9GsKhB-Yd1eGPdq8NHw5mj_9xpRT5Ggmkw
@companyId=0193ea0e-12b0-704e-b888-cf085466b612
@yearId=0193ea0e-12b6-72bf-ae19-45a43fdd19c4
# @categoryId=01932b09-e357-7998-9a52-513d73aef4ba
@unitId=0193ea0e-12ca-71ad-a5fd-ec3aa58be8d3
@productId=01932b09-e357-7998-9a52-513d73aef4ba
@productId2=0193cd7f-616b-7aac-9f47-0befc8f791a5

### Get all stock invoices
GET {{baseUrl}}/api/companies/{{companyId}}/years/{{yearId}}/stock-invoices
Content-Type: application/json
Authorization: Bearer {{token}}

### Get stock invoice by id
GET {{baseUrl}}/api/companies/{{companyId}}/years/{{yearId}}/stock-invoices/0193d058-a12c-7ccf-9886-16fd767d7a71
Content-Type: application/json
Authorization: Bearer {{token}}


### Create stock invoice
POST {{baseUrl}}/api/companies/{{companyId}}/years/{{yearId}}/stock-invoices
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "invoiceDate": "2024-12-17",
  "totalQty": "10",
  "totalAmount": "25000",
  "notes": "This is test stock invoice",
  "lineItems": [
    {
      "productId": "{{productId}}",
      "unitId": "{{unitId}}",
      "gtn": "tbd",
      "qty": "100",
      "rate": "25000",
      "price": "2000000",
      "discountPct": 10,
      "taxPct": 5,
      "lineTotal": "12500",
      "marginPct": 10
    },
    {
      "productId": "{{productId2}}",
      "unitId": "{{unitId}}",
      "gtn": "tbd",
      "qty": "5",
      "rate": "12500",
      "price": "12500",
      "discountPct": 10,
      "taxPct": 5,
      "lineTotal": "12500",
      "marginPct": 10
    }
  ]
}

### Update stock invoice
PUT {{baseUrl}}/api/companies/{{companyId}}/years/{{yearId}}/stock-invoices/d768a1ac-b2a3-4500-9b9d-7d5d00030f95
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "code": "FY-2024-25",
  "beginDate": "2024-04-01",
  "endDate": "2025-03-31"
}

### Delete stock invoice
DELETE {{baseUrl}}/api/companies/{{companyId}}/years/{{yearId}}/stock-invoices/d768a1ac-b2a3-4500-9b9d-7d5d00030f95
Content-Type: application/json
Authorization: Bearer {{token}}