@baseUrl=http://localhost:4000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxOTJhODM2LWIxYjktNzMzNy1hNmE3LWYzNTYzOGExNjJlNSIsImlhdCI6MTcyOTM5OTAwOSwiZXhwIjoxNzI5NDg1NDA5fQ.DHQ5ECTwwyl53ygaqnhFQFEsOo8vIVWLYCqjP7QoWos

### Get all units
GET {{baseUrl}}/api/companies/0192a838-1ddf-7337-a6a8-0838ddcea2fb/units
Content-Type: application/json
Authorization: Bearer {{token}}

### Get unit by id
GET {{baseUrl}}/api/companies/0192a838-1ddf-7337-a6a8-0838ddcea2fb/units/0192a84e-db7e-7224-afc5-afeb110e1227
Content-Type: application/json
Authorization: Bearer {{token}}


### Create unit
POST {{baseUrl}}/api/companies/0192a838-1ddf-7337-a6a8-0838ddcea2fb/units
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "code": "NO.",
  "name": "Number",
  "description": "Numbers"
}

### Update unit
PUT {{baseUrl}}/api/companies/0192a838-1ddf-7337-a6a8-0838ddcea2fb/units/d768a1ac-b2a3-4500-9b9d-7d5d00030f95
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "tbala",
  "firstName": "Balamurugan",
  "lastName": "Thanikachalam",
  "email": "tbala@fandatech.net"
}

### Delete unit
DELETE {{baseUrl}}/api/companies/0192a838-1ddf-7337-a6a8-0838ddcea2fb/units/4d5dc30e-43f1-4ec1-9300-0285a95c768c
Content-Type: application/json
Authorization: Bearer {{token}}