@baseUrl=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMTkyZmM1ZS0wMDkzLTdjY2MtYTIwYS1kYzg0NGE1YmFkMWMiLCJpYXQiOjE3MzA4MTI0MjQsImV4cCI6NDg4NDQxMjQyNH0.kpqWbQXwp9GsKhB-Yd1eGPdq8NHw5mj_9xpRT5Ggmkw
@companyId=0193c5eb-c2d8-7118-a7b1-aa7767181dbd
@unitId=0192fc47-ac9b-7001-a290-788777a046a1

### Get all units
GET {{baseUrl}}/api/companies/{{companyId}}/units
Content-Type: application/json
Authorization: Bearer {{token}}

### Get unit by id
GET {{baseUrl}}/api/companies/{{companyId}}/units/0192a84e-db7e-7224-afc5-afeb110e1227
Content-Type: application/json
Authorization: Bearer {{token}}


### Create unit
POST {{baseUrl}}/api/companies/{{companyId}}/units
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "unitId": "{{unitId}}",
  "code": "DEFAULT",
  "name": "Default Unit",
  "description": "Default Unit"
}

### Update unit
PUT {{baseUrl}}/api/companies/{{companyId}}/units/d768a1ac-b2a3-4500-9b9d-7d5d00030f95
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "tbala",
  "firstName": "Balamurugan",
  "lastName": "Thanikachalam",
  "email": "tbala@fandatech.net"
}

### Delete unit
DELETE {{baseUrl}}/api/companies/{{companyId}}/units/01930141-ef9a-7bba-915a-3e4ed9df0c18
Content-Type: application/json
Authorization: Bearer {{token}}