@baseUrl=http://localhost:4000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMTkyZmM1ZS0wMDkzLTdjY2MtYTIwYS1kYzg0NGE1YmFkMWMiLCJpYXQiOjE3MzA4MTI0MjQsImV4cCI6NDg4NDQxMjQyNH0.kpqWbQXwp9GsKhB-Yd1eGPdq8NHw5mj_9xpRT5Ggmkw
@adminUserId=0192fc5e-0093-7ccc-a20a-dc844a5bad1c

### Get all users
GET {{baseUrl}}/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

### Get user by id
GET {{baseUrl}}/api/users/{{adminUserId}}
Content-Type: application/json
Authorization: Bearer {{token}}


### Create user
POST {{baseUrl}}/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "vyuvan",
  "password": "Welcome!23",
  "email": "vyuvan@gmail.com",
  "firstName": "Yuvan",
  "lastName": "Vinayagam"
}

### Update user
PUT {{baseUrl}}/api/users/{{adminUserId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "admin",
  "firstName": "Fanda",
  "lastName": "Admin",
  "email": "admin@fandatech.net"
}

### Delete user
DELETE {{baseUrl}}/api/users/4d5dc30e-43f1-4ec1-9300-0285a95c768c
Content-Type: application/json
Authorization: Bearer {{token}}